### PR TITLE
Respect wffc override for blank block disks

### LINKED ISSUE #2915: Blank disk with block volume mode stuck in ImportScheduled for WFFC storage class
**What happened**:
Created a blank DV with block volume mode for WFFC storage class, and found that it is stuck in ImportScheduled phase

**What you expected to happen**:
Expect the disk to be in Succeeded phase.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

1. Have a storage class that supports block mode and WFFC
2. Create a blank DV as below:
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: empty-disk
spec:
  source:
    blank: {}
  storage:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: block-sc
    volumeMode: Block
```
3. Observe that the dv is stuck in ImportScheduled phase.

**Additional context**:

Adding the annotation `cdi.kubevirt.io/storage.usePopulator: "false"`  to the dv allows the import to fall back to the old way and bypass the issue. 
    
**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.57.0

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
We currently don't support the wffc override for blank block disks,
while there may be some use cases where that is desired.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2915 

**Special notes for your reviewer**:

**Release note**:

```release-note
BugFix: wffc override not respected for blank block disks
```

### CODE REVIEW

File: tests/import_test.go [hunk 1]
```diff
@@ -611,6 +616,15 @@ var _ = Describe("Importer Test Suite-Block_device", func() {
...
 		}, controllerSkipPVCCompleteTimeout, assertionPollInterval).Should(BeTrue())
 		Expect(err).ToNot(HaveOccurred())
+
+		err = utils.WaitForPersistentVolumeClaimPhase(f.K8sClient, pvc.Namespace, v1.ClaimBound, pvc.Name)
+		Expect(err).ToNot(HaveOccurred())
+	},
+		Entry("[test_id:4972] with first consumer", true),
+		Entry("with bind immediate annotation", false),
+	)
+	It("Should create blank raw image for block PV", func() {
```
Comment (alromeros) [inline tests/import_test.go:626]: Code leftover, looks good otherwise. Thanks for the PR!

Comment (akalenyu) [reply tests/import_test.go]: whoops thx

File: pkg/controller/import-controller.go [hunk 2]
```diff
@@ -220,12 +220,11 @@ func (r *ImportReconciler) Reconcile(_ context.Context, req reconcile.Request) (
 	volumeMode := cc.GetVolumeMode(pvc)
 	if volumeMode == corev1.PersistentVolumeBlock && pvc.GetAnnotations()[cc.AnnSource] == cc.SourceNone && pvc.GetAnnotations()[cc.AnnPreallocationRequested] != "true" {
 		log.V(1).Info("attempting to create blank disk for block mode, this is a no-op, marking pvc with pod-phase succeeded")
-		if pvc.GetAnnotations() == nil {
-			pvc.SetAnnotations(make(map[string]string, 0))
-		}
-		pvc.GetAnnotations()[cc.AnnPodPhase] = string(corev1.PodSucceeded)
-		if err := r.updatePVC(pvc, log); err != nil {
-			return reconcile.Result{}, errors.WithMessage(err, fmt.Sprintf("could not update pvc %q annotation and/or label", pvc.Name))
+		if pvc.Status.Phase == corev1.ClaimBound {
```
Comment (awels) [inline pkg/controller/import-controller.go:223]: So I am not sure about this. We purposely mark the PVC succeeded in the blank block case regardless of if it is bound or not. This is so that KubeVirt won't think it can't use the PVC. Once we have a consumer kubernetes will bind the PVC and everything resolves itself.

This was pre-populator logic. Now I don't really see how populators would affect blank block volumes at all, since there is no population. Maybe I am missing something.

Comment (akalenyu) [reply pkg/controller/import-controller.go:223]: > This is so that KubeVirt won't think it can't use the PVC

KubeVirt should be fine with WFFC Pending PVCs/DV:
https://github.com/kubevirt/kubevirt/pull/9812

Comment (awels) [reply pkg/controller/import-controller.go:223]: Right, so I am trying to understand why we want this particular check here. I don't think we even want to use populators, unless maybe pre-allocation is set to true.

Comment (akalenyu) [reply pkg/controller/import-controller.go:223]: The problem is if we stop using populators with this flow, we're back at the doppelganger pod solution

Comment (awels) [reply pkg/controller/import-controller.go:223]: For the blank volume without pre-allocation case, there is no need for the doppel ganger. It is 'populated' already considering there is nothing we have to do. It just gets bound when the VM starts, but it is still exactly the way we want it. With pre-allocation, I would expect our populator to attempt the pr-eallocation at the appropriate time.

**Comment by akalenyu** [comment]
/hold

Taking a step back. This works with HonorWaitForFirstConsumer enabled creating a bind pod.
The only thing that is broken is using `bind.immediate` with block blank DVs (because no consumer will be created)

File: pkg/controller/import-controller.go (hunk 2 above)
Comment (lzang) [reply pkg/controller/import-controller.go:223]: In my case, the PVC is not in bound state. It is in WFFC. 
If the issue is because I didn't enable HonorWaitForFirstConsumer feature gate, is there any side effect or behavior change of enabling this feature gate?

Comment (akalenyu) [reply pkg/controller/import-controller.go:223]: So we've been going with this feature for quite a few releases now,
it basically means we respect WFFC binding by not creating any worker pods until PVCs get scheduled.

Is there any particular use case you have that would require bypassing WFFC behavior,
and bind PVCs randomly? Or will these blank disks be consumed by a VM?

**Comment by akalenyu** [comment]
@lzang @awels PTAL

File: pkg/controller/import-controller.go [hunk 3]
```diff
@@ -215,20 +215,6 @@ func (r *ImportReconciler) Reconcile(_ context.Context, req reconcile.Request) (
...
-		log.V(1).Info("attempting to create blank disk for block mode, this is a no-op, marking pvc with pod-phase succeeded")
-		if pvc.GetAnnotations() == nil {
-			pvc.SetAnnotations(make(map[string]string, 0))
-		}
-		pvc.GetAnnotations()[cc.AnnPodPhase] = string(corev1.PodSucceeded)
-		if err := r.updatePVC(pvc, log); err != nil {
-			return reconcile.Result{}, errors.WithMessage(err, fmt.Sprintf("could not update pvc %q annotation and/or label", pvc.Name))
-		}
-		return reconcile.Result{}, nil
-	}
```
Comment (lzang) [inline pkg/controller/import-controller.go:231]: I don't get why this is not needed any more from looking at the CL.  Could you please clarify why? 
Does this logic work for both populator case and non-populator case?

Comment (awels) [reply pkg/controller/import-controller.go:231]: Essentially this was a short cut for one particular case (blank disk, no preallocation) and removing it will cause a pod to be created, but per the rest of this PR, that pod won't do anything. What it will do is follow the rest of the logic when creating a population pod, which should work for both populator and non populator cases, as well as HonorWaitForFirstConsumer set or not.
