### PR TITLE
Use the correct API group for import pod owner reference

### LINKED ISSUE #292: Wrong API Group specified for blockOwnerDeletion
When attempting to import into a PVC the following error appears in the logs...

E0731 17:53:43.133558       1 import-controller.go:206] error processing pvc "default/golden-pvc": importer pod API create errored: pods "importer-golden-pvc-t5zvn" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion apps/v1 Kind PersistentVolumeClaim: allowed by openshift authorizer, no matches for apps/, Kind=PersistentVolumeClaim

### PR DESCRIPTION
**Pull request by aglitke**
The api group should be v1 not appsv1.  Fixes #292.

Signed-off-by: Adam Litke <alitke@redhat.com>

### CODE REVIEW

File: pkg/controller/util.go [hunk 1]
```diff
@@ -479,7 +479,7 @@ func MakeCloneTargetPodSpec(image, verbose, pullPolicy string, pvc *v1.Persisten
 									},
 								},
 							},
-							Namespaces: []string{podAffinityNamespace},
+							Namespaces:  []string{podAffinityNamespace},
```
Comment (jeffvance) [inline pkg/controller/util.go]: super nit: did `gofmt` add the trailing space?

**Comment by jeffvance** [comment]
lgtm

File: pkg/controller/util.go (hunk 1 above)
Comment (aglitke) [reply pkg/controller/util.go]: yes

**Comment by mhenriks** [comment]
appsv1 is referenced in util_test.go as well so should probably be changed there as well

**Comment by jeffvance** [comment]
@aglitke 
> appsv1 is referenced in util_test.go as well so should probably be changed there as well
 Do you want this to be a separate pr or added to your pr here?
