### PR TITLE
Set pod restart policy to "OnFailure" and cleanup succesful pods

### LINKED ISSUE #400: It looks like the cdi controller is not eventually consistent
It looks like the `DataVolume` will only try to import an image once and then just goes to a failed state. I think that such a behaviour is fine for workloads (Pod, VMI) but for infrastructure components it is very unusual (I actually can't remember to have seen such a behaviour).

The main issue with that is, that all other controllers which want to use data volumes will also have to manage retry-logic for them to make the system eventually consistent again. Normally controller include retry-logic (including back-off) themselves. Also the whole way on how controller are intended to be written with e.g. client-go are designed with that assumption in mind.

Also PVCs work that way. If a storage provisioner does not have enough space left to back the PVC with a PV, the PVC does not go to a final failed state. Instead, as soon as enough space is left, the provisioner will eventually create a PV and the PVC will go to a bound state.

It is not impossible that a controller can add a proper-retry logic for a DataVolume to itself (see for instance https://github.com/kubevirt/kubevirt/pull/1475), but it significantly increases the complexity of every consumer.

What do you think?

### PR DESCRIPTION
**Pull request by j-griffith**
**What this PR does / why we need it**:

This patch does two things:
1. We modify the restart policy from never to "OnFailure" for the
    Importer (we already did this for Upload, and we don't want to do it yet
    for the Clone pods)
2. Upon successful completion delete our worker pods
    We're not doing this on failed pods right now because in general an
    admin will likely want to inspect the pod to see why it failed.

**Special notes for your reviewer**:

The first question someone will likely ask is "well what about a node
failure", well in the case of a node failure for CDI we have a bigger
outstanding issue remaining to figure out how to deal with volume
connections.  We can't just simply reschedule the job.

Partial Fixes #400

**Release note**:

```Image pods now use RestartOnFailure (Cloner pods are the only ones that still RestartNever)
PODS are now deleted upon successful completion

```

### CODE REVIEW

File: pkg/controller/util.go [hunk 1]
```diff
@@ -721,3 +729,20 @@ func MakeUploadServiceSpec(name string, pvc *v1.PersistentVolumeClaim) *v1.Servi
 	}
 	return service
 }
+
```
Comment (j-griffith) [inline pkg/controller/util.go]: At some point I'd like to clean up util.go, probably have a pod.go file for all the pod related stuff and share it across the controllers, but for now util is a nice dumping ground for this sort of thing.

File: pkg/controller/util.go [hunk 2]
```diff
@@ -27,6 +28,13 @@ const DataVolName = "cdi-data-vol"
 const ImagePathName = "image-path"
 const socketPathName = "socket-path"
 
+type podDeleteRequest struct {
```
Comment (j-griffith) [inline pkg/controller/util.go]: I set up a request here because we're still a bit disjointed in our controllers.  In the future, we'd ideally do something like an interface and share the bulk of the Controller functions, but for now I'm cheating and use a request struct so you can shove in all the nitty gritty details.

File: pkg/controller/util.go [hunk 3]
```diff
@@ -721,3 +729,20 @@ func MakeUploadServiceSpec(name string, pvc *v1.PersistentVolumeClaim) *v1.Servi
...
+		return nil
+	}
+	if err == nil && pod.DeletionTimestamp == nil {
+		err = req.k8sClient.CoreV1().Pods(req.namespace).Delete(req.podName, &metav1.DeleteOptions{})
+		if k8serrors.IsNotFound(err) {
+			return nil
+		}
+	}
+	if err != nil {
+		glog.V(1).Infof("error encountered deleting pod (%s): %s", req.podName, err.Error())
```
Comment (j-griffith) [inline pkg/controller/util.go]: For those that don't check or care about an error here, we log it so there's a record of something going south

File: pkg/controller/upload-controller.go [hunk 4]
```diff
@@ -370,7 +370,16 @@ func (c *UploadController) syncHandler(key string) error {
...
+		// we're using a req struct for now until we can normalize the controllers a bit more and share things like lister, client etc
+		// this way it's easy to stuff everything into an easy request struct, and can extend aditional behaviors if we want going forward
+		dReq := podDeleteRequest{
+			namespace: pvc.Namespace,
+			podName:   resourceName,
+			podLister: c.podLister,
+			k8sClient: c.client,
+		}
+
+		err = deletePod(dReq)
```
Comment (mhenriks) [inline pkg/controller/upload-controller.go]: This code path deletes the pod/service when the upload annotation is removed (maybe the user changed their mind about uploading).

To delete the pod when an upload succeeds, add something around here:  https://github.com/kubevirt/containerized-data-importer/blob/6327c899a2eb7d546ccf557a0578a4fcf664ef98/pkg/controller/upload-controller.go#L418

Comment (j-griffith) [reply pkg/controller/upload-controller.go]: Ahh!  I honestly didn't notice that was a user update on the annotation.  I'll take a look at adding another defer podDelete after success, thanks!

**Comment by j-griffith** [comment]
ci test please

**Comment by j-griffith** [comment]
ci test please

**Comment by awels** [comment]
There are a couple of unit tests that are failing on the restart policy change. They are expecting never, and are getting OnFailure.

**Comment by j-griffith** [comment]
ci test please

File: tests/cloner_test.go [hunk 5]
```diff
@@ -94,9 +96,9 @@ func doCloneTest(f *framework.Framework, targetNs *v1.Namespace) {
 		return srcNode == tgtNode
 	}, cloneCompleteTimeout, assertionPollInterval).Should(BeTrue())
 
-	err = f.WaitTimeoutForPodStatus(sourcePod.Name, v1.PodSucceeded, cloneCompleteTimeout)
+	err = f.WaitTimeoutForPodStatus(sourcePod.Name, v1.PodPending, shortTimeout)
```
Comment (j-griffith) [inline tests/cloner_test.go]: It looks like there are some timing differences between the CI system and my workstation here such that we don't make this check before the delete grace period has completed.  I'll swap this to a wait for delete and we should be in good shape, I'll also include a comment explaining what's going on.

File: pkg/controller/clone-controller.go [hunk 6]
```diff
@@ -168,6 +170,23 @@ func (cc *CloneController) processPvcItem(pvc *v1.PersistentVolumeClaim) error {
 	return nil
 }
 
+func (cc *CloneController) deleteClonePods(namespace, srcName, tgtName string) {
```
[the remark this answers is not in the document]
Comment (awels) [reply pkg/controller/clone-controller.go]: Doesn't look like deletePod retries on failure, it just returns an error code. However this code ignores the error code. I guess its not a huge deal on deleting the pods.

**Comment by awels** [comment]
lgtm, want me to merge?

**Comment by davidvossel** [comment]
@j-griffith what happens with partial uploads/clones. When the pod retries, will it be able to recover and try again if the file already exists?

**Comment by j-griffith** [comment]
@davidvossel   I'll verify the partial upload case; It looks like we'll overwrite the img if it's there but I need to test that and make sure it works as expected.  We did not add the restart policy to the Clone PODs yet.   I had marked the PR as a "partial" fix until we decide on the best way to address synchronizing the clone pods.
