### PR TITLE
Append Labels From DV to Importer Pod

### LINKED ISSUE #3674: Can we allow for custom labels on the importer pod, or at least add istio.io/dataplane-mode: none to support Ambient Mesh
We are running CDI `1.59.0` on Kubevirt `1.3.0`. Things have been going well until we start testing with Ambient Mesh using Istio. CDI already accounts for *sidecar-based* Istio with the annotation of `sidecar.istio.io/inject: 'false'` on the importer-pod by default, which makes the transfer bypass the Istio sidecar:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cdi.kubevirt.io/storage.createdByController: 'yes'
    linkerd.io/inject: disabled
    sidecar.istio.io/inject: 'false'
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    cdi.kubevirt.io: importer
    prometheus.cdi.kubevirt.io: 'true'
  name: importer-prime-16bec903-1771-4e03-bad7-fa2029ccd30b
  namespace: test-vm
```

Problem is, Ambient Mesh uses a different mechanism, a **label** of `istio.io/dataplane-mode: none`. Since there is no mechanism to put this on, the importer pod launches, runs for around 2-5 min (it varies), and eventually blows up with this error:

```
I0311 18:47:50.961109       1 importer.go:103] Starting importer
I0311 18:47:50.962691       1 importer.go:173] begin import process
I0311 18:47:50.962752       1 s3-datasource.go:149] Endpoint rcd1kubes3clu1.mi.corp.xxxxx.com
I0311 18:47:50.962775       1 s3-datasource.go:153] bucket templates
I0311 18:47:50.962779       1 s3-datasource.go:154] object win2022-gold.img.gz
I0311 18:47:50.979721       1 http-datasource.go:263] Attempting to get certs from /certs/ca.pem
I0311 18:47:51.054017       1 data-processor.go:358] Calculating available size
I0311 18:47:51.055005       1 data-processor.go:366] Checking out block volume size.
I0311 18:47:51.055024       1 data-processor.go:378] Request image size not empty.
I0311 18:47:51.055038       1 data-processor.go:383] Target size 85Gi.
I0311 18:47:51.055289       1 data-processor.go:257] New phase: TransferDataFile
I0311 18:47:51.056493       1 util.go:188] Writing data...
E0311 18:50:14.174653       1 util.go:190] Unable to write file from dataReader: unexpected EOF
E0311 18:50:14.174754       1 data-processor.go:253] unexpected EOF
unable to write to file
kubevirt.io/containerized-data-importer/pkg/util.StreamDataToFile
	pkg/util/util.go:192
kubevirt.io/containerized-data-importer/pkg/importer.(*S3DataSource).TransferFile
	pkg/importer/s3-datasource.go:118
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func4
	pkg/importer/data-processor.go:200
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:250
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:159
main.handleImport
	cmd/cdi-importer/importer.go:179
main.main
	cmd/cdi-importer/importer.go:144
runtime.main
	GOROOT/src/runtime/proc.go:267
runtime.goexit
	src/runtime/asm_amd64.s:1650
Unable to transfer source data to target file
```

Envoy seemingly can't handle this transfer going through it, so we want to bypass it all together. 

**TL;DR** - Can we add functionality so we can add custom labels (ideal) or if not, at least add support for Ambient Istio by adding `istio.io/dataplane-mode: none`

### PR DESCRIPTION
**Pull request by Dsanatar**
Fixes #3674 

During the creation of the Importer Pod, append any labels from the PVC. This allows for labels to be passed from a Data Volume.

```release-note
Labels on DataVolumes are now copied to the importer pod
```

### CODE REVIEW

**Comment by Dsanatar** [comment]
`/retest`

File: tests/import_test.go [hunk 1]
```diff
@@ -2125,6 +2125,51 @@ var _ = Describe("Containerdisk envs to PVC labels", func() {
...
+		testNonKubevirtVal = "none"
+	)
+
+	It("Import pod should inherit any labels from Data Volume", func() {
+
+		dataVolume := utils.NewDataVolumeWithHTTPImport("label-test", "100Mi", fmt.Sprintf(utils.TinyCoreIsoURL, f.CdiInstallNs))
+		dataVolume.Annotations[controller.AnnImmediateBinding] = "true"
+		dataVolume.Annotations[controller.AnnPodRetainAfterCompletion] = "true"
+
+		dataVolume.ObjectMeta.Labels = map[string]string{
```
Comment (awels) [inline tests/import_test.go:2144]: You don't have to specify ObjectMeta here, so just `dataVolume.Labels` will do.

File: pkg/util/util_test.go [hunk 2]
```diff
@@ -183,3 +183,39 @@ var _ = Describe("Usable Space calculation", func() {
 		Entry("40Gi virtual size, large overhead to be 40Gi if <= 40Gi and 41Gi if > 40Gi", 40*Gi, largeOverhead),
 	)
 })
+
+var _ = Describe("Append Labels", func() {
+
+	someLabels := map[string]string{
```
Comment (awels) [inline pkg/util/util_test.go:189]: I would make this a `DescribeTable` since we are just testing various permutations of inputs, and comparing it against an output. Something like this:
```go
var (
  someLabels, emtpyLabels, existingLabels, expectedMergedLabels map[string]string

BeforeEach(func() {
  someLabels = map[string]string{
    "label1": "val1",
    "label2": "val2",
    "label3": "val3",
  }
  emptyLabels = make(map[string]string)
  existingLabels = map[string]string{
    "label4": "val4",
    "label5": "val5",
  }
  expectedMergedLabels = map[string]string{
    "label1": "val1",
    "label2": "val2",
    "label3": "val3",
    "label4": "val4",
    "label5": "val5",
  }
})
DescribeTable("should properly merge labels", func(original, merge, expected map[string]string) {
  MergeLabels(original, merge)
  Expect(original).To(HaveLen(len(expected)))
  for k,v := range original {
    Expect(expected[k]).To(Equal(original[k]))
  }
}, 
Entry("original empty", someLabels, emptyLabels, someLabels),
Entry("original has values", someLabels, existingLabels, expectedMergedLabels),
Entry("original empty, adding empty", emptyLabels, emptyLabels, emptyLabels),
Entry("original has values, adding empty", emptyLabels, existingLabels, existingLabels),
)
```
This allows me to try a variety of permutations with a single check. Also by using the BeforeEach, I can reset the variables to a know good value before each time an entry is invoked.

**Review by awels — COMMENTED** [review]
Looks like the failures are because the labels are not being applied to the importer pod. That is what the error is indicating.

**Review by awels — APPROVED** [review]
/approve
