### PR TITLE
fix: Label Copy for Importer Pods

### LINKED ISSUE #3988: Clarification on copying labels from source PVC to prime PVC
**What happened**:
We noticed that CDI copies labels from the original PVC to the prime PVC, which is a temporary object created during the import process. Could you clarify the reasoning behind this behavior?

**What you expected to happen**:
Prime PVC should not inherit user-defined labels unless necessary for CDI operations.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
Create a PVC with custom labels (e.g., app=myvm).
Trigger an import using CDI (e.g., DataVolume or VolumeImportSource with source: http://quay.io/nirsof/cirros:0.6.2-1).
Observe that the prime PVC created during the process inherits the labels from the original PVC.

**Additional context**:
Prime PVC inherits all labels from the original PVC.

- Is this intentional and required for CDI functionality?
- Could this lead to unintended side effects if external controllers interpret these labels?
- Would it make sense to avoid copying user-defined labels?

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): `image: quay.io/kubevirt/cdi-controller:v1.63.0`
- Kubernetes version (use `kubectl version`): 
```
# kubectl version
Client Version: v1.34.1
Kustomize Version: v5.7.1
Server Version: v1.34.0
```
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): RHEL9.6
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

CC: [nirsof@gmail.com](mailto:nirsof@gmail.com)

### PR DESCRIPTION
**Pull request by Dsanatar**
**What this PR does / why we need it**:

Issue found with how previous implementation https://github.com/kubevirt/containerized-data-importer/pull/3744 copied labels to Importer Pod by means of the prime pvc. Instead of copying form target pvc -> prime pvc -> pod, skip copying to the prime pvc and instead get the labels from target pvc by using the prime pvc's owner ref.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3988

**Special notes for your reviewer**:

**Release note**:

```release-note
Copy Labels from PVC to Importer Pod
```

### CODE REVIEW

**Comment by Dsanatar** [comment]
/cc @akalenyu 
I saw your suggestion about using the `AnnEventSource` logic for this but it seems we can get what we need from the ownerRef of the prime pvc just as easily. thoughts?

**Review by Acedus — COMMENTED** [review]
Looks good! Can we add a UT for this?

**Review by akalenyu — COMMENTED** [review]
> /cc @akalenyu I saw your suggestion about using the `AnnEventSource` logic for this but it seems we can get what we need from the ownerRef of the prime pvc just as easily. thoughts?

This looks good tbh, quite simple

I didn't realize we only ever tackled importer pods (upload/clone omitted), is that desired?

BTW, would you mind converting the e2e tests to unit tests https://github.com/kubevirt/containerized-data-importer/blob/2c88a8aaffd6af3b51bc0d4b3a4c564ffa2a5918/tests/import_test.go#L2100 I don't think there's much value over unit in this case

**Comment by Dsanatar** [comment]
@akalenyu  ack, just converted the func test to unit tests

> I didn't realize we only ever tackled importer pods (upload/clone omitted), is that desired?
> 
The original issue was only related to importer pods https://github.com/kubevirt/containerized-data-importer/issues/3674 however if the need is there, it shouldn't be too difficult to implement this for upload and clone as well

**Comment by akalenyu** [comment]
/test pull-cdi-unit-test
/test pull-cdi-goveralls
unrelated/quay down

**Review by akalenyu — COMMENTED** [review]
/approve

thank you, FYI @nirs

File: pkg/controller/populators/populator-base.go [hunk 1]
```diff
@@ -231,7 +231,6 @@ func (r *ReconcilerBase) createPVCPrime(pvc *corev1.PersistentVolumeClaim, sourc
 	}
 	cc.CopyAllowedAnnotations(pvc, pvcPrime)
 	util.SetRecommendedLabels(pvcPrime, r.installerLabels, "cdi-controller")
-	util.MergeLabels(pvc.Labels, pvcPrime.Labels)
```
Comment (nirs) [inline pkg/controller/populators/populator-base.go:234]: This merged labels from target pvc into the prime pvc?

File: pkg/controller/import-controller.go [hunk 2]
```diff
@@ -941,8 +910,22 @@ func createImporterPod(ctx context.Context, log logr.Logger, client client.Clien
...
+		pvc := &corev1.PersistentVolumeClaim{}
+		if err := client.Get(context.TODO(), types.NamespacedName{Namespace: args.pvc.Namespace, Name: ownerRef.Name}, pvc); err != nil {
+			return nil, err
+		}
+		srcLabels = pvc.GetLabels()
+	}
+
 	// add any labels from pvc to the importer pod
-	util.MergeLabels(args.pvc.Labels, pod.Labels)
+	util.MergeLabels(srcLabels, pod.Labels)
```
Comment (nirs) [inline pkg/controller/import-controller.go:928]: And this merges labels from the target pvc into the pod?

So the prime pvc does copy application labels now, right?

**Review by nirs — COMMENTED** [review]
Can you share example prime pvc before this change and after this change?

File: pkg/controller/import-controller.go (hunk 2 above)
Comment (Dsanatar) [reply pkg/controller/import-controller.go:928]: yes, that is correct. the original implementation allowed for custom labels to be passed from PVCs to importer pods. As you pointed out, when we are using `DataVolumes` (or populators) we were doing this by copying the labels from the target PVC to the prime pvc so that we could merge them when creating the importer pod.

However, these changes make it so we skip copying the labels to the prime pvc

File: pkg/controller/import-controller_test.go [hunk 3]
```diff
@@ -907,6 +908,64 @@ var _ = Describe("Create Importer Pod", func() {
...
+		}
+
+		reconciler := createImportReconciler(objects...)
+
+		pod, err := createImporterPod(context.TODO(), reconciler.log, reconciler.client, podArgs, map[string]string{})
+		Expect(err).ToNot(HaveOccurred())
+
+		By("Verifying pod has labels from target PVC")
+		Expect(pod.Labels).To(HaveKeyWithValue("custom-label", "value"))
+		if isPopulator {
```
Comment (alromeros) [inline pkg/controller/import-controller_test.go:960]: Maybe also add a check to ensure the prime PVC doesn’t have the target PVC labels?

Comment (Dsanatar) [reply pkg/controller/import-controller_test.go:960]: yea good point. Since that requires reconciling at the populator layer, I added a new UT there

**Comment by nirs** [comment]
@Dsanatar which upstream kubevirt version will include this fix?

**Comment by Dsanatar** [comment]
@nirs the linked issue https://github.com/kubevirt/containerized-data-importer/issues/3988 mentions using CDI v1.63 so this fix will be backported to that version. The equivalent kubevirt release is version 1.6

**Comment by akalenyu** [comment]
@nirs we would have to make a release that includes this commit in all those versions. maybe we could start with just 1.65.1?

**Comment by nirs** [comment]
Including the fix in the latest version would be good enough for us.
