### PR TITLE
Fix cluster-clean

### LINKED ISSUE #774: Delete CDI Namespace hangs forever
/kind bug

**What happened**:

After deploying CDI to my Kubernetes 1.14 cluster, I wanted to quickly remove it so I just used `kubectl delete ns cdi`.  All of the objects were in fact cleaned up succesfully, however the CDI namespace itself appears to hang in terminating state indefinitely.

I believe this also occurs with Kubevirt as well, perhaps something in the operator implementation, or maybe a side effect of running on external clusters?

**What you expected to happen**:

I expect all CDI resources to be removed, including the CDI Namespace

**How to reproduce it (as minimally and precisely as possible)**:

Deploy CDI to a cluster, wait for it to finish deployment, then run `kubectl delete ns cdi`

**Anything else we need to know?**:

**Environment**:

Running from master against an external 1.14 cluster

### PR DESCRIPTION
**Pull request by j-griffith**
We were missing some resources in the cleanup on make cluster-clean
(when running against an external cluster).  We also weren't patching
any of the finalizers so the result is a delete of the cdi namespace
would hang in terminating state forever.

This change explicitly checks all resources on the cluster for a cdi
label and it also patches the cdi objects to clear out the finalizer.

Fixes #774

```release-note
NONE
```

### CODE REVIEW

File: cluster/clean.sh [hunk 1]
```diff
@@ -21,25 +27,49 @@ if [ -f "${OPERATOR_MANIFEST}" ]; then
...
-    _kubectl -n ${i} delete secrets -l 'operator.cdi.kubevirt.io' -l 'cdi.kubevirt.io'
-    _kubectl -n ${i} delete configmaps -l 'operator.cdi.kubevirt.io' -l 'cdi.kubevirt.io'
-    _kubectl -n ${i} delete pvc -l 'operator.cdi.kubevirt.io' -l 'cdi.kubevirt.io'
-    _kubectl -n ${i} delete pods -l 'operator.cdi.kubevirt.io' -l 'cdi.kubevirt.io'
-    _kubectl -n ${i} delete rolebinding -l 'operator.cdi.kubevirt.io' -l 'cdi.kubevirt.io'
-    _kubectl -n ${i} delete roles -l 'operator.cdi.kubevirt.io' -l 'cdi.kubevirt.io'
-    _kubectl -n ${i} delete serviceaccounts -l 'operator.cdi.kubevirt.io' -l 'cdi.kubevirt.io'
+for n in ${NAMESPACES[@]}; do
+  for label in ${labels[@]}; do
+    _kubectl -n ${n} delete deployment -l ${lael}
```
Comment (awels) [inline cluster/clean.sh]: you have a typo, should be label not lael

Comment (j-griffith) [reply cluster/clean.sh]: Done, thanks!

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
ci test please
