### PR TITLE
cdi-uploadserver: healthcheck and application use same port

### LINKED ISSUE #3450: upload-controller.go: Upload pod is marked as ready when it is not serving yet
**What happened**:

upload-controller.go marks the upload Pod as ready once all containers are ready, see:

https://github.com/kubevirt/containerized-data-importer/blob/d08e24523d904cb70324fdf57535c100b81ce8ca/pkg/controller/upload-controller.go#L524

This is not enough on a heavily loaded cluster, because although all containers are ready, the Pod might still not be serving the upload server yet. Because upload-controller.go marked the Pod as ready, the upload proxy will try to connect to it prematurely, which leads to failure of the upload with a message like:

```
error in upload-proxy: http: proxy error: dial tcp 10.97.83.53:443: connect: connection refused
```

See

https://github.com/kubevirt/containerized-data-importer/blob/d08e24523d904cb70324fdf57535c100b81ce8ca/pkg/uploadproxy/uploadproxy.go#L291

https://github.com/kubevirt/containerized-data-importer/blob/d08e24523d904cb70324fdf57535c100b81ce8ca/pkg/uploadproxy/uploadproxy.go#L324

**What you expected to happen**:

upload-controller.go should wait for the upload Pod to be serving before marking it as ready.

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:

As observed in https://github.com/kubevirt/kubevirt/pull/12925

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by mhenriks**
healthcheck used to be on a dedicated port for "reasons" and by that I mean I was too lazy to properly set up the tls configuration and check authz in upload handlers

**What this PR does / why we need it**:

This one is for @akalenyu and @0xFelix: I know I told you this wasn't possible but here you go.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3450

**Special notes for your reviewer**:

**Release note**:

```release-note
BugFix: cdi-uploadserver reporting readiness more honestly resulting in concurrent image uploads failing less
```

### CODE REVIEW

File: pkg/uploadserver/uploadserver.go [hunk 1]
```diff
@@ -264,13 +246,16 @@ func (app *uploadServerApp) Run() (*RunResult, error) {
...
+			return nil, errors.New("invalid TLS config")
+		}
 		return nil, nil
 	}
 
 	//nolint:gosec // False positive: Min version is not known statically
 	config := &tls.Config{
 		CipherSuites: app.config.CryptoConfig.CipherSuites,
-		ClientAuth:   tls.RequireAndVerifyClientCert,
+		ClientAuth:   tls.VerifyClientCertIfGiven,
```
Comment (akalenyu) [inline pkg/uploadserver/uploadserver.go:258]: trying to understand if there are implications to VerifyClientCertIfGiven. can't a request now get further ahead?
or is `if len(r.TLS.VerifiedChains) == 0 {` guarding that

File: pkg/uploadserver/uploadserver.go [hunk 2]
```diff
@@ -264,13 +246,16 @@ func (app *uploadServerApp) Run() (*RunResult, error) {
...
+		if !app.config.Insecure {
+			return nil, errors.New("invalid TLS config")
+		}
 		return nil, nil
 	}
 
 	//nolint:gosec // False positive: Min version is not known statically
 	config := &tls.Config{
 		CipherSuites: app.config.CryptoConfig.CipherSuites,
-		ClientAuth:   tls.RequireAndVerifyClientCert,
```
Comment (akalenyu) [inline pkg/uploadserver/uploadserver.go:273]: trying to understand if there are implications to VerifyClientCertIfGiven. can't a request now get further ahead?
or is `if len(r.TLS.VerifiedChains) == 0 {` guarding that

**Review by akalenyu — COMMENTED** [review]
This is great! maybe rework the release note a bit and attach the related issue? https://github.com/kubevirt/containerized-data-importer/issues/3450

**Comment by akalenyu** [comment]
/test pull-containerized-data-importer-e2e-ceph
tests didn't even run

**Comment by akalenyu** [comment]
> > This is great! maybe rework the release note a bit and attach the related issue? #3450
> 
> How can the release note be better? Feel free to edit yourself

made the change. wdyt

**Review by awels — APPROVED** [review]

**Comment by 0xFelix** [comment]
@mhenriks @akalenyu Does this mean we can drop the retry from virtctl imageupload again? Does this also mean we can make the functests for it run in parallel again?

**Comment by 0xFelix** [comment]
@akalenyu Might still be worth a try? I'd love to at least see the tests running in parallel.

**Comment by akalenyu** [comment]
we will release CDI soon and when that percolates to kubevirt/kubevirt (through automation) we could give that a try

**Comment by akalenyu** [comment]
> @akalenyu Interesting, that would narrow it down a bit further. How hard is it to implement this?

I would really hate for CDI to know anything about endpointslices (and add the RBAC for them in all namespaces)
But just for the sake of PoC, why not
I find it weird that there is no service field providing this indication..

**Comment by 0xFelix** [comment]
@akalenyu Agree with you. Only for a PoC and only if you have the time.

**Comment by akalenyu** [comment]
> @akalenyu Agree with you. Only for a PoC and only if you have the time.

https://github.com/kubevirt/containerized-data-importer/pull/3545
