### PR TITLE
fix controller unit test to be namespace aware

### LINKED ISSUE #84: add importer unit tests for multiple namespaces
[pr 82](https://github.com/kubevirt/containerized-data-importer/pull/82) adds support for multiple namespaces, meaning a pvc does not need to live in the "golden" ns.

### PR DESCRIPTION
**Pull request by screeley44**
fixes #84 

After some investigation with Jeff we discovered that `namespace` is needed when the queue is created to properly find the importer pod.

### CODE REVIEW

File: pkg/controller/controller_test.go [hunk 1]
```diff
@@ -39,7 +40,17 @@ var _ = Describe("Controller", func() {
 		expectError   bool
 	}
 
-	setUpInformer := func(obj *v1.PersistentVolumeClaim, op operation, pvcName string) {
+	setUpInformer := func(obj *v1.PersistentVolumeClaim, op operation, pvcName string, ns string) {
```
Comment (jeffvance) [inline pkg/controller/controller_test.go]: nit: `(... op operation, ns, pvcName string) { ...`

File: pkg/controller/controller_test.go [hunk 2]
```diff
@@ -39,7 +40,17 @@ var _ = Describe("Controller", func() {
...
+		// build queue value of ns + "/" + pvcName if exists
+		var buf bytes.Buffer
+		if len(ns) > 0 {
+			buf.WriteString(ns)
+			buf.WriteString("/")
+			buf.WriteString(pvcName)
+		} else {
+			buf.WriteString(pvcName)
+		}
+
```
Comment (jeffvance) [inline pkg/controller/controller_test.go]: I think this is simpler and more typical in k8s code (replaces use of _bytes_ and buf block above):
```
// build queue value of work queue to be "ns/name" or just "name" if ns is blank
queueKey := pvcName
if len(ns) > 0 {
     queueKey = fmt.Sprintf("%s/%s", ns, pvcName)
}

File: pkg/controller/controller_test.go [hunk 3]
```diff
@@ -51,7 +62,7 @@ var _ = Describe("Controller", func() {
 		if op == opAdd {
 			pvcListWatcher.Add(obj)
 			objSource.Add(obj)
-			queue.Add(pvcName)
+			queue.Add(buf.String())
```
Comment (jeffvance) [inline pkg/controller/controller_test.go]: `queue.Add(queueKey)`

File: pkg/controller/controller_test.go [hunk 4]
```diff
@@ -106,7 +117,7 @@ var _ = Describe("Controller", func() {
 			pvcObj.Annotations[AnnEndpoint] = ep
 			pvcObj.Namespace = ns
 			By("invoking the controller")
-			setUpInformer(pvcObj, opAdd, pvcName)
+			setUpInformer(pvcObj, opAdd, pvcName, ns)
```
Comment (jeffvance) [inline pkg/controller/controller_test.go]: nit: `etUpInformer(pvcObj, opAdd, ns, pvcName)`

**Comment by jeffvance** [comment]
lgtm
