### PR TITLE
fix issue #2323: Cross namespace smart clone not cleaning up

### LINKED ISSUE #2323: Smart clone leaves "tmp" PVC in pending, deletes PV
**What happened**:

##**Smart Clone leaves "tmp" pvc in pending when cloning from one namespace to another**##
FYI Rook managed Ceph / Ceph-CSI is being used

-----------------------------------------------------------------------------------------------------

**What you expected to happen**:
##**Smart Clone should** ##
1. Create a snapshot of the source PVC
2. Create a PVC from the created snapshot
3. Delete the snapshot
4. Expand the new PVC if requested size is larger than the snapshot
5. If the DataVolume is in a different namespace, "transfer" the PVC to the target namespace via Namespace Transfer API
6. No "tmp" Snaphot PVC should be left behind

-----------------------------------------------------------------------------------------------------

**How to reproduce it (as minimally and precisely as possible)**:

##**CDI import to Datavolume PVC in "golden" namespace** (kubectl apply below)##
```apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: golden-centos-dv
  namespace: golden
spec:
  source:
    http:
      url: "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
  pvc:
    storageClassName: rook-ceph-block
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
```

##**DataVolume clone PVC into new namespace customer1** (kubectl apply below)##
```apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: clone-centos-dv-customer1
  namespace: customer1
spec:
  source:
    pvc:
      namespace: golden
      name: golden-centos-dv 
  pvc:
    storageClassName: rook-ceph-block
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi 
```
-----------------------------------------------------------------------------------------------------

**Additional context**:

##**CDI to pull down image in namespace "golden"**##
```**---DV ---**
NAMESPACE   NAME                PHASE       PROGRESS   RESTARTS   AGE
golden      golden-centos-dv    Succeeded   100.0%                10m
**---PV---**
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                         STORAGECLASS      REASON   AGE     VOLUMEMODE
pvc-0dbeacb9-d433-4e8e-ad41-422f10545431   10Gi       RWO            Delete           Bound    golden/golden-centos-dv       rook-ceph-block            10m     Block
**---PVC---**
NAMESPACE   NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE     VOLUMEMODE
golden      golden-centos-dv    Bound    pvc-0dbeacb9-d433-4e8e-ad41-422f10545431   10Gi       RWO            rook-ceph-block   10m     Block
```
-----------------------------------------------------------------------------------------------------

##**Smart Clone (clone DV PVC image to namespace "customer1" from "golden" ns)**##
```**---DV---**
NAMESPACE   NAME                        PHASE       PROGRESS   RESTARTS   AGE
customer1   clone-centos-dv-customer1   Succeeded   N/A                   2m
golden      golden-centos-dv            Succeeded   100.0%                15m

**---PV---**
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                 STORAGECLASS      REASON   AGE     VOLUMEMODE
pvc-0dbeacb9-d433-4e8e-ad41-422f10545431   10Gi       RWO            Delete           Bound    golden/golden-centos-dv               rook-ceph-block            15m     Block

pvc-31584650-0e8e-49f3-acb1-c91079fa5f56   10Gi       RWO            Delete           Bound    customer1/clone-centos-dv-customer1   rook-ceph-block            117s    Block

**---PVC---**
NAMESPACE   NAME                                           STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE     VOLUMEMODE
customer1   clone-centos-dv-customer1                      Bound     pvc-31584650-0e8e-49f3-acb1-c91079fa5f56   10Gi       RWO            rook-ceph-block   117s    Block

**golden      cdi-tmp-a76ca33a-56a6-4b2e-b375-6665073ac3ce**   **Pending**                                                                        rook-ceph-block   117s    Block

golden      golden-centos-dv                               Bound     pvc-0dbeacb9-d433-4e8e-ad41-422f10545431   10Gi       RWO            rook-ceph-block   15m     Block
```
-----------------------------------------------------------------------------------------------------

##**Ceph pool image dump during Smart Cloning (while true; do rbd ls -p $pool; rbd ls -p $pool | grep -c csi; end)**##
```**--Start--**
csi-vol-24f48bea-ebfa-11ec-9315-8a0dd827368e  <-- golden image (in K8S ns "golden")

**--Next transition (snapshot image create)--**
csi-vol-24f48bea-ebfa-11ec-9315-8a0dd827368e  <-- golden image (in K8S ns "golden")
csi-snap-0d6f7131-ebfc-11ec-9315-8a0dd827368e <-- snapshot of golden image

**--Next transition (snapshot and now clone image--**
csi-vol-24f48bea-ebfa-11ec-9315-8a0dd827368e  <-- golden image (in K8S ns "golden")
csi-snap-0d6f7131-ebfc-11ec-9315-8a0dd827368e <-- snapshot of golden image
csi-vol-0e76e29f-ebfc-11ec-9315-8a0dd827368e  <-- clone of golden (in K8S ns "customer1")

**--Final transition (snapshot image was DELETED though PVC remained in K8S)--**
csi-vol-24f48bea-ebfa-11ec-9315-8a0dd827368e  <-- golden image (in K8S ns "golden")
csi-vol-0e76e29f-ebfc-11ec-9315-8a0dd827368e  <-- clone of golden (in K8S ns "customer1")
```
-----------------------------------------------------------------------------------------------------

**Environment**:
- Component versions
[operator.cdi.kubevirt.io/createVersion=v1.49.0](http://operator.cdi.kubevirt.io/createVersion=v1.49.0)
[controller-gen.kubebuilder.io/version](http://controller-gen.kubebuilder.io/version): v0.7.0
[k8s.gcr.io/sig-storage/csi-attacher:v3.4.0](http://k8s.gcr.io/sig-storage/csi-attacher:v3.4.0)
[k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0](http://k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0)
[k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0](http://k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0)
[k8s.gcr.io/sig-storage/csi-resizer:v1.4.0](http://k8s.gcr.io/sig-storage/csi-resizer:v1.4.0)
[k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1](http://k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1)
[quay.io/cephcsi/cephcsi:v3.6.1](http://quay.io/cephcsi/cephcsi:v3.6.1)
virt-operator:v0.53.1

- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by mhenriks**
1.  Make sure smart clone controller does not create PVCs if VolumeSnapshot deleted

2.  Make sure that ObjectTransfer cleanup occurs.

Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2323

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/datavolume-controller.go [hunk 1]
```diff
@@ -746,7 +748,15 @@ func (r *DatavolumeReconciler) reconcileClone(log logr.Logger,
 			}
 			fallthrough
 		case SmartClone:
-			return r.finishClone(log, datavolume, pvc, pvcSpec, transferName, selectedCloneStrategy)
+			if !pvcPopulated && datavolume.Status.Phase != cdiv1.Succeeded {
+				return r.finishClone(log, datavolume, pvc, pvcSpec, transferName, selectedCloneStrategy)
+			}
+
+			if isCrossNamespaceClone(datavolume) && datavolume.Status.Phase == cdiv1.Succeeded {
```
Comment (brybacki) [inline pkg/controller/datavolume-controller.go:755]: ok, I think I get - because of skipping populated we skipped this cleanup

File: tests/cloner_test.go [hunk 2]
```diff
@@ -47,7 +48,7 @@ const (
 	crossVolumeModeCloneMD5NumBytes  = 100000
 )
 
-var _ = Describe("all clone tests", func() {
+var _ = FDescribe("all clone tests", func() {
```
Comment (awels) [inline tests/cloner_test.go:51]: Left over `FDescribe`?

Comment (mhenriks) [reply tests/cloner_test.go]: yes, ugh
