### PR TITLE
fix possible race condition by checking annotation

### LINKED ISSUE #120: need to clean up some general flow and error recovery scenarios
1.  If importer pod fails to create - don't want to forget the key in processItem
        - to ensure we try to process again

2.  importer race condition - multiple imports on a single pvc
```
$ kubectl logs importer-golden-pvcmzqld
I0425 17:36:37.917054       5 importer.go:35] main: Starting importer
I0425 17:36:37.919191       5 importer.go:50] main: importing file "tinyCore.qcow2.gz"
W0425 17:36:37.919256       5 dataStream.go:42] NewDataStream: IMPORTER_ACCESS_KEY_ID and/or IMPORTER_SECRET_KEY env variables are empty
I0425 17:36:37.919470       5 dataStream.go:71] Using S3 client to get data
I0425 17:36:37.919657       5 dataStream.go:78] Attempting to get object "s3://kubevirt-images/tinyCore.qcow2.gz" via S3 client
I0425 17:36:37.919850       5 importer.go:58] Beginning import from "/tinyCore.qcow2.gz"
I0425 17:36:37.919871       5 decompress.go:26] UnpackData: checking compressed and/or archive for file "tinyCore.qcow2.gz"
I0425 17:36:37.919875       5 decompress.go:45] DecompressData: checking if "tinyCore.qcow2.gz" is compressed
I0425 17:36:38.268947       5 decompress.go:59] DecompressData: decompressed "tinyCore.qcow2.gz"
I0425 17:36:38.268995       5 decompress.go:70] DearchiveData: checking if "tinyCore.qcow2" is an archive file
I0425 17:36:38.269281       5 util.go:44] StreamDataToFile: begin import...
I0425 17:36:52.916024       5 importer.go:88] main: converting qcow2 image to raw
I0425 17:36:52.949694       5 importer.go:98] main: Import complete, exiting
jcope@jonMBP | ~/.../kubevirt/manifests
$ kubectl logs importer-golden-pvcs9ntq
I0425 17:36:39.276378       7 importer.go:35] main: Starting importer
I0425 17:36:39.276943       7 importer.go:50] main: importing file "tinyCore.qcow2.gz"
W0425 17:36:39.276975       7 dataStream.go:42] NewDataStream: IMPORTER_ACCESS_KEY_ID and/or IMPORTER_SECRET_KEY env variables are empty
I0425 17:36:39.277832       7 dataStream.go:71] Using S3 client to get data
I0425 17:36:39.277960       7 dataStream.go:78] Attempting to get object "s3://kubevirt-images/tinyCore.qcow2.gz" via S3 client
I0425 17:36:39.278006       7 importer.go:58] Beginning import from "/tinyCore.qcow2.gz"
I0425 17:36:39.278050       7 decompress.go:26] UnpackData: checking compressed and/or archive for file "tinyCore.qcow2.gz"
I0425 17:36:39.278063       7 decompress.go:45] DecompressData: checking if "tinyCore.qcow2.gz" is compressed
I0425 17:36:39.536339       7 decompress.go:59] DecompressData: decompressed "tinyCore.qcow2.gz"
I0425 17:36:39.536358       7 decompress.go:70] DearchiveData: checking if "tinyCore.qcow2" is an archive file
I0425 17:36:39.536531       7 util.go:44] StreamDataToFile: begin import...
I0425 17:36:41.136349       7 importer.go:88] main: converting qcow2 image to raw
I0425 17:36:41.166394       7 importer.go:98] main: Import complete, exiting
```

### PR DESCRIPTION
**Pull request by screeley44**
fixes #120 

and maybe #118

### CODE REVIEW

**Comment by copejon** [comment]
LGTM

File: pkg/controller/controller.go [hunk 1]
```diff
@@ -130,6 +130,10 @@ func (c *Controller) processItem(pvc *v1.PersistentVolumeClaim) error {
 	if secretName == "" {
 		glog.Infof("processItem: no secret will be supplied to endpoint %q\n", ep)
 	}
+	if metav1.HasAnnotation(pvc.ObjectMeta, AnnImportPod) {
```
Comment (jeffvance) [inline pkg/controller/controller.go]: The `glog` on L87 should be moved to below L90.

Comment (jeffvance) [reply pkg/controller/controller.go]: If the cdi controller operates in its own goroutine and there is only 1 cdi controller running (_threadiness==1), why do we have to worry about a race cond here?

File: pkg/controller/controller.go [hunk 2]
```diff
@@ -144,6 +158,25 @@ func (c *Controller) processItem(pvc *v1.PersistentVolumeClaim) error {
 	if secretName == "" {
 		glog.Infof("processItem: no secret will be supplied to endpoint %q\n", ep)
 	}
+
```
Comment (jeffvance) [inline pkg/controller/controller.go]: This looks like exact dup code from above. Can you move it to a helper func?

File: pkg/controller/controller.go [hunk 3]
```diff
@@ -103,27 +102,12 @@ func (c *Controller) ProcessNextItem() bool {
...
-				}
-			}
-		} else {
-			return c.forgetKey(fmt.Sprintf("processNextItem: pvc has annotation %q, indicating this is being processed or was already processed once, skipping pvc\n", AnnImportPod), key)
-		}
-	} else {
-		// this pvc does not contain our endpoint annotation.
-		return c.forgetKey(fmt.Sprintf("processNextItem: annotation %q not found, skipping pvc\n", AnnEndpoint), key)
+	if !c.checkIfShouldQueuePVC(pvc, "processNextItem") {
+		return c.forgetKey(fmt.Sprintf("processNextItem: annotation %q not found or pvc %s is already bing worked, skipping pvc\n", AnnEndpoint, pvc.Name), key)
```
Comment (jeffvance) [inline pkg/controller/controller.go]: typo: _being_

File: pkg/controller/util.go [hunk 4]
```diff
@@ -33,6 +33,37 @@ func (c *Controller) pvcFromKey(key interface{}) (*v1.PersistentVolumeClaim, err
...
+		} else {
+			glog.Infof("%s: pvc has annotation %q, indicating this is being processed or was already processed once, skipping pvc\n", method, AnnImportPod)
+			return false
+		}
+	} else {
+		// this pvc does not contain our endpoint annotation.
+		glog.Infof("%s: annotation %q not found, skipping pvc\n", method, AnnEndpoint)
+		return false
+	}
+	return true
```
Comment (jeffvance) [inline pkg/controller/util.go]: It looks like this `return` is reached if L48 we have err, or L50 no `AnnImportPod`.
What should be returned if the `Get` api call fails?

Comment (screeley44) [reply pkg/controller/util.go]: it's reached if we have our EndPoint anno AND also we have the ImportPod anno

Comment (screeley44) [reply pkg/controller/util.go]: if we fail on our API call, we keep going, it's a best effort in my opinion

Comment (jeffvance) [reply pkg/controller/util.go]: My take on a refactor here:
```
func (c *Controller) checkIfShouldQueuePVC(pvc *v1.PersistentVolumeClaim, method string) bool {
 	if !metav1.HasAnnotation(pvc.ObjectMeta, AnnEndpoint) {
             glog.Infof("%s: annotation %q not found, skipping pvc\n", method, AnnEndpoint)
             return false
        }
        if metav1.HasAnnotation(pvc.ObjectMeta, AnnImportPod) {
             glog.Infof("%s: pvc has annotation %q, indicating this is being processed or was already processed once, skipping pvc\n", method, AnnImportPod)
             return false
        }
 	// secondary check, just in case, fetching latest pvc object if available to help mitigate race and timing issues
 	// with latency between the store and work queue to double check if we are already processing.
 	glog.Infof("%s: checking latest version of Get pvc for inprocess annotation", method)
 	latest, err := c.clientset.CoreV1().PersistentVolumeClaims(pvc.Namespace).Get(pvc.Name, metav1.GetOptions{})
 	if err != nil {
            glog.Errorf('unexpected....')
            return false
        }
 	// checking if we are already processing this request based on latest known Get()
 	if metav1.HasAnnotation(latest.ObjectMeta, AnnImportPod) {
 		glog.Infof("processNextItem: latest Get on pvc reveals that annotation %q exists indicating this was already processed once, skipping pvc\n", method, AnnImportPod)
 		return false
 	}
 	return true
}
```

Comment (screeley44) [reply pkg/controller/util.go]: if you error because the api fails, you potentially throw away a valid pvc... no?
