### PR TITLE
Fix Longhorn Filesystem capabilities

### LINKED ISSUE #3680: CDI Upgrade from 1.59.1 to 1.59.2 causes failed import of disks
**What happened**:
I upgraded the CDI operator from 1.59.1 to 1.59.2. After that, DataVolume imports on my longhorn-rwx storage class fails with the following error: 

```
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Warning  FailedScheduling        82s                default-scheduler        0/4 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
  Warning  FailedScheduling        81s                default-scheduler        0/4 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
  Normal   Scheduled               79s                default-scheduler        Successfully assigned virtualmachines/importer-prime-ef9556e0-cdd4-445d-9c38-4921f3680bc5 to kube2
  Normal   SuccessfulAttachVolume  44s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-ac31cb2a-24d3-47e3-b734-691857476bf0"
  Warning  FailedMapVolume         11s (x7 over 44s)  kubelet                  MapVolume.MapPodDevice failed for volume "pvc-ac31cb2a-24d3-47e3-b734-691857476bf0" : rpc error: code = Internal desc = failed to bind mount "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-ac31cb2a-24d3-47e3-b734-691857476bf0/pvc-ac31cb2a-24d3-47e3-b734-691857476bf0" at "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-ac31cb2a-24d3-47e3-b734-691857476bf0/3c72acb2-8e4e-401e-8d6c-36432bb395fb": mount failed: exit status 32
Mounting command: mount
Mounting arguments:  -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-ac31cb2a-24d3-47e3-b734-691857476bf0/pvc-ac31cb2a-24d3-47e3-b734-691857476bf0 /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-ac31cb2a-24d3-47e3-b734-691857476bf0/3c72acb2-8e4e-401e-8d6c-36432bb395fb
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-ac31cb2a-24d3-47e3-b734-691857476bf0/3c72acb2-8e4e-401e-8d6c-36432bb395fb: special device /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-ac31cb2a-24d3-47e3-b734-691857476bf0/pvc-ac31cb2a-24d3-47e3-b734-691857476bf0 does not exist.
       dmesg(1) may have more information after failed mount system call.
```
This perfectly works on 1.59.1 though.

**What you expected to happen**:
Importing a disk to my Storageclass with longhorn-rwx

**How to reproduce it (as minimally and precisely as possible)**:
- Create a DataVolume import on on my storageclass longhorn-rwx

**Additional context**:

This is the storageclass used at the moment:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-rwx
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  nfsOptions: "vers=4.2,noresvport,softerr,timeo=600,retrans=5"
```

**Environment**:
- CDI version: 1.59.2
- Kubernetes version (use `kubectl version`): 1.31.6
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Talos Linux 1.9.3
- Kernel (e.g. `uname -a`): 6.12.11-talos
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by arnongilboa**
**What this PR does / why we need it**:
When the storage class parameters specifies `migratable: "true"` it supports RWX Block but not Filesystem:
https://github.com/longhorn/longhorn/blob/master/enhancements/20241206-v2-volume-live-migration.md https://github.com/longhorn/longhorn/blob/master/enhancements/20210216-volume-live-migration.md

RWX Filesystem is preferred when `nfsOptions` are specified:
https://longhorn.io/docs/1.8.1/nodes-and-volumes/volumes/rwx-volumes/

RWO Filesystem is preferred when `fsType` is specified.

**Which issue(s) this PR fixes**:
Fixes #3680

**Special notes for your reviewer**:

**Release note**:
```release-note
Fix Longhorn Filesystem capabilities
```

### CODE REVIEW

**Comment by arnongilboa** [comment]
/hold
Until @MichaelTrip provides the DV spec in #3680 so we can better understand the issue there.

File: pkg/storagecapabilities/storagecapabilities.go [hunk 1]
```diff
@@ -360,10 +362,16 @@ var storageClassToProvisionerKeyMapper = map[string]func(sc *storagev1.StorageCl
 		}
 	},
 	"driver.longhorn.io": func(sc *storagev1.StorageClass) string {
-		migratable := sc.Parameters["migratable"]
-		if migratable == "true" {
+		if sc.Parameters["migratable"] == "true" {
```
Comment (akalenyu) [inline pkg/storagecapabilities/storagecapabilities.go:365]: does the order matter? couldn't it be for instance migratable and fs, in which case we'll return rwx

Comment (arnongilboa) [reply pkg/storagecapabilities/storagecapabilities.go:365]: As noted in the description, `migratable` is only supported for block, and I guess we would like to prefer it even if the SC is mis-configured with fsType.

**Comment by akalenyu** [comment]
@arnongilboa the hold on this PR is yours FYI
